/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;
import koneksi.Koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import model.Officer;
/**
 *
 * @author LENOVO
 */
public class FormOfficers extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormOfficers.class.getName());
    private DefaultTableModel model;
    String id;
    /**
     * Creates new form FormOfficers
     */
    public FormOfficers() {
        initComponents();
        setLocationRelativeTo(null);
        tampilData();
    }
private void tampilData() {

    model = new DefaultTableModel();

    model.addColumn("ID");
    model.addColumn("Reg Number");
    model.addColumn("Nama");
    model.addColumn("Email");
    model.addColumn("Segment");

    tblOfficers.setModel(model);

    try {

        Connection c = Koneksi.getKoneksi();

        String sql = "SELECT * FROM officers";

        PreparedStatement p = c.prepareStatement(sql);

        ResultSet r = p.executeQuery();

        while (r.next()) {

            Object[] data = {
                r.getString("id"),
                r.getString("official_reg_number"),
                r.getString("name"),
                r.getString("email"),
                r.getString("segment")
            };

            model.addRow(data);

        }

    } catch (Exception e) {

        JOptionPane.showMessageDialog(null, e);

    }

}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtReg = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtSegment = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOfficers = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtEmail.addActionListener(this::txtEmailActionPerformed);

        txtSegment.addActionListener(this::txtSegmentActionPerformed);

        btnSimpan.setFont(new java.awt.Font("Segoe UI Semibold", 2, 12)); // NOI18N
        btnSimpan.setText("SIMPAN");
        btnSimpan.addActionListener(this::btnSimpanActionPerformed);

        btnEdit.setFont(new java.awt.Font("Segoe UI Semibold", 2, 12)); // NOI18N
        btnEdit.setText("EDIT");
        btnEdit.addActionListener(this::btnEditActionPerformed);

        btnHapus.setFont(new java.awt.Font("Segoe UI Semibold", 2, 12)); // NOI18N
        btnHapus.setText("HAPUS");
        btnHapus.addActionListener(this::btnHapusActionPerformed);

        btnReset.setFont(new java.awt.Font("Segoe UI Semibold", 2, 12)); // NOI18N
        btnReset.setText("RESET");
        btnReset.addActionListener(this::btnResetActionPerformed);

        tblOfficers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblOfficers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblOfficersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblOfficers);

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 2, 12)); // NOI18N
        jLabel1.setText("REG");

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 2, 12)); // NOI18N
        jLabel2.setText("NAMA");

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 2, 12)); // NOI18N
        jLabel3.setText("EMAIL");

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 2, 12)); // NOI18N
        jLabel4.setText("SEGMENT");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtReg, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEdit)
                            .addComponent(btnSimpan)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSegment, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(btnHapus))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnReset))))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSimpan))
                .addGap(1, 1, 1)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEdit))
                .addGap(3, 3, 3)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSegment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset))
                .addGap(57, 57, 57))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
    
try {

        Officer officer = new Officer();

        officer.setOfficialRegNumber(txtReg.getText());
        officer.setName(txtNama.getText());
        officer.setEmail(txtEmail.getText());
        officer.setSegment(txtSegment.getText());

        Connection c = Koneksi.getKoneksi();

        String sql = "INSERT INTO officers "
                + "(official_reg_number, name, email, segment) "
                + "VALUES (?, ?, ?, ?)";

        PreparedStatement p = c.prepareStatement(sql);

        p.setString(1, officer.getOfficialRegNumber());
        p.setString(2, officer.getName());
        p.setString(3, officer.getEmail());
        p.setString(4, officer.getSegment());

        p.executeUpdate();

        JOptionPane.showMessageDialog(null, "Data berhasil disimpan");

        tampilData();

        btnResetActionPerformed(null);

    } catch (Exception e) {

        JOptionPane.showMessageDialog(null, e);

    }

    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
           txtReg.setText("");
    txtNama.setText("");
    txtEmail.setText("");
    txtSegment.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
       try {

        Connection c = Koneksi.getKoneksi();

        String sql = "DELETE FROM officers WHERE id=?";

        PreparedStatement p = c.prepareStatement(sql);

        p.setString(1, id);

        p.executeUpdate();

        JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");

        tampilData();

    } catch (Exception e) {

        JOptionPane.showMessageDialog(null, e);

    }  
    }//GEN-LAST:event_btnHapusActionPerformed

    private void tblOfficersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblOfficersMouseClicked
            int baris = tblOfficers.getSelectedRow();

    id = tblOfficers.getValueAt(baris, 0).toString();

    txtReg.setText(tblOfficers.getValueAt(baris, 1).toString());
    txtNama.setText(tblOfficers.getValueAt(baris, 2).toString());
    txtEmail.setText(tblOfficers.getValueAt(baris, 3).toString());
    txtSegment.setText(tblOfficers.getValueAt(baris, 4).toString());
    }//GEN-LAST:event_tblOfficersMouseClicked

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
         try {

        Officer officer = new Officer();

        officer.setOfficialRegNumber(txtReg.getText());
        officer.setName(txtNama.getText());
        officer.setEmail(txtEmail.getText());
        officer.setSegment(txtSegment.getText());

        Connection c = Koneksi.getKoneksi();

        String sql = "UPDATE officers SET "
                + "official_reg_number=?, "
                + "name=?, "
                + "email=?, "
                + "segment=? "
                + "WHERE id=?";

        PreparedStatement p = c.prepareStatement(sql);

        p.setString(1, officer.getOfficialRegNumber());
        p.setString(2, officer.getName());
        p.setString(3, officer.getEmail());
        p.setString(4, officer.getSegment());
        p.setString(5, id);

        p.executeUpdate();

        JOptionPane.showMessageDialog(null, "Data berhasil diubah");

        tampilData();

        btnResetActionPerformed(null);

    } catch (Exception e) {

        JOptionPane.showMessageDialog(null, e);

    }
    }//GEN-LAST:event_btnEditActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtSegmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSegmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSegmentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormOfficers().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblOfficers;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtReg;
    private javax.swing.JTextField txtSegment;
    // End of variables declaration//GEN-END:variables
}
