/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import koneksi.Koneksi;
import model.Drive;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class FormDrives extends javax.swing.JFrame {
    private DefaultTableModel model;
    String id;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormDrives.class.getName());

    /**
     * Creates new form FormDrives
     */
    public FormDrives() {
        initComponents();
        loadOfficer();
        loadVehicle();
        tampilData();
        setLocationRelativeTo(null);
    }

    private void tampilData() {

    model = new DefaultTableModel();

    model.addColumn("ID");
    model.addColumn("Officer");
    model.addColumn("Vehicle");
    model.addColumn("Latitude");
    model.addColumn("Longitude");
    model.addColumn("Date");
    model.addColumn("Active");

    tblDrives.setModel(model);

    try {

        Connection c = Koneksi.getKoneksi();

        String sql =
        "SELECT drives.id, officers.name, vehicles.model, "
        + "drives.latitude, drives.longitude, "
        + "drives.date, drives.active "
        + "FROM drives "
        + "JOIN officers ON drives.officer_id = officers.id "
        + "JOIN vehicles ON drives.vehicle_id = vehicles.id";

        PreparedStatement p = c.prepareStatement(sql);

        ResultSet r = p.executeQuery();

        while (r.next()) {

            Object[] data = {

                r.getString("id"),
                r.getString("name"),
                r.getString("model"),
                r.getString("latitude"),
                r.getString("longitude"),
                r.getString("date"),
                r.getString("active")

            };

            model.addRow(data);

        }

    } catch (Exception e) {

        JOptionPane.showMessageDialog(null, e);

    }

}
    private void loadOfficer() {

    try {

        Connection c = Koneksi.getKoneksi();

        String sql = "SELECT * FROM officers";

        PreparedStatement p = c.prepareStatement(sql);

        ResultSet r = p.executeQuery();

        while (r.next()) {

            cbOfficer.addItem(r.getString("name"));

        }

    } catch (Exception e) {

        JOptionPane.showMessageDialog(null, e);

    }

}
    
private void loadVehicle() {

    try {

        Connection c = Koneksi.getKoneksi();

        String sql = "SELECT * FROM vehicles";

        PreparedStatement p = c.prepareStatement(sql);

        ResultSet r = p.executeQuery();

        while (r.next()) {

            cbVehicle.addItem(r.getString("model"));

        }

    } catch (Exception e) {

        JOptionPane.showMessageDialog(null, e);

    }

}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbOfficer = new javax.swing.JComboBox<>();
        cbVehicle = new javax.swing.JComboBox<>();
        txtLatitude = new javax.swing.JTextField();
        txtLongitude = new javax.swing.JTextField();
        txtDate = new javax.swing.JTextField();
        chkActive = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDrives = new javax.swing.JTable();
        btnSimpan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbOfficer.addActionListener(this::cbOfficerActionPerformed);

        chkActive.setFont(new java.awt.Font("Segoe UI Semibold", 2, 12)); // NOI18N
        chkActive.setText("ACTIVE");

        tblDrives.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblDrives);

        btnSimpan.setFont(new java.awt.Font("Segoe UI Semibold", 2, 12)); // NOI18N
        btnSimpan.setText("SIMPAN");
        btnSimpan.addActionListener(this::btnSimpanActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 2, 12)); // NOI18N
        jLabel1.setText("OFFICER");

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 2, 12)); // NOI18N
        jLabel2.setText("VEHICLE");

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 2, 12)); // NOI18N
        jLabel3.setText("LATITUDE");

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 2, 12)); // NOI18N
        jLabel4.setText("LONGTITUDE");

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 2, 12)); // NOI18N
        jLabel5.setText("TAHUN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkActive)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLongitude, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(cbVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbOfficer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSimpan)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtLatitude, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbOfficer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jLabel2)
                        .addGap(1, 1, 1)
                        .addComponent(cbVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLatitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jLabel4)
                        .addGap(1, 1, 1)
                        .addComponent(txtLongitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chkActive)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSimpan))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        try {

        Drive drive = new Drive();

        Connection c = Koneksi.getKoneksi();

        // AMBIL ID OFFICER
        String sqlOfficer =
        "SELECT id FROM officers WHERE name=?";

        PreparedStatement pOfficer =
        c.prepareStatement(sqlOfficer);

        pOfficer.setString(1,
        cbOfficer.getSelectedItem().toString());

        ResultSet rOfficer =
        pOfficer.executeQuery();

        String officerId = "";

        if (rOfficer.next()) {

            officerId = rOfficer.getString("id");

        }

        // AMBIL ID VEHICLE
        String sqlVehicle =
        "SELECT id FROM vehicles WHERE model=?";

        PreparedStatement pVehicle =
        c.prepareStatement(sqlVehicle);

        pVehicle.setString(1,
        cbVehicle.getSelectedItem().toString());

        ResultSet rVehicle =
        pVehicle.executeQuery();

        String vehicleId = "";

        if (rVehicle.next()) {

            vehicleId = rVehicle.getString("id");

        }

        // SET OBJECT OOP
        drive.setOfficerId(officerId);
        drive.setVehicleId(vehicleId);
        drive.setLatitude(txtLatitude.getText());
        drive.setLongitude(txtLongitude.getText());
        drive.setDate(txtDate.getText());
        drive.setActive(chkActive.isSelected());

        // INSERT
        String sql =
        "INSERT INTO drives "
        + "(officer_id, vehicle_id, active, latitude, longitude, date) "
        + "VALUES (?, ?, ?, ?, ?, ?)";

        PreparedStatement p =
        c.prepareStatement(sql);

        p.setString(1, drive.getOfficerId());
        p.setString(2, drive.getVehicleId());
        p.setBoolean(3, drive.isActive());
        p.setString(4, drive.getLatitude());
        p.setString(5, drive.getLongitude());
        p.setString(6, drive.getDate());

        p.executeUpdate();

        JOptionPane.showMessageDialog(null,
        "Data monitoring berhasil disimpan");

        tampilData();

    } catch (Exception e) {

        JOptionPane.showMessageDialog(null, e);

    }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void cbOfficerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbOfficerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbOfficerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormDrives().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cbOfficer;
    private javax.swing.JComboBox<String> cbVehicle;
    private javax.swing.JCheckBox chkActive;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDrives;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtLatitude;
    private javax.swing.JTextField txtLongitude;
    // End of variables declaration//GEN-END:variables
}
